EverythingSmartHome/everything-presence-one

static/_sass/custom/custom.scss
(the top red bar is my browser UI)
**BEFORE**
**AFTER** solution 1: bigger container, same text size
The line under the title isn't "continuing" with the one under the search field
**AFTER** solution 2: same container, smaller text size
There is no line section
I started with solution 1, but I may prefer 2 finally.
As you wish !
Fixes #44
=> Fix doc title overflow under browser UI

everything-presence-one.yaml
I did some improvements to have better default and naming in Home Assistant.
- Use entity naming (by adding friendly name : https://esphome.io/changelog/2023.2.0.html#friendly-name)
- room is gone because it's not needed aymore with this. By renaming the device in HA, all entity ids will be renamed.
- entity ID will have this format : `{device}_{mac}_{entity}` (example : `sensor.everything_presence_one_d723f3_occupancy`)
- Hide some entities by default 
- safe mode
- restart
- status led
- mmwave led
- mmwave switch
- ~~Put some entities in diagnostic (they will not appear in the default dashboard)~~
- ~~mmwave~~
- ~~PIR~~
- Convert mmwave from switch to light
- Add icons 🧑‍🎨
Feel free to add some feedback if there is something you like/dislike or something I can improve 🙂
=> Entity naming and improvements

everything-presence-one-beta.yaml
This change adds 4 configurable distance zones. By default, only a single start and end distance is shown to the user and the other 3 zones are a "hidden" entity in Home Assistant.
If you enable them, you can set up to 4 zones to monitor, which allows you to exclude certain distances from being monitored. This is particularly useful for excluding certain devices from triggering movement, such as a fan.
For example, using the distance zones, if you have a fan that is located 2m from the sensor, you could set as follows:
Zone 1: 0cm to 195cm
Zone 2: 240cm to 405cm
Meaning the distance of 195cm to 240cm is not monitored and therefor triggered by the sensor.
This release changes the entity name of the original "distance" entity (used to be a single slider for setting max distance). It also …
=> Add distance zones

SEN0395_distance.h, everything-presence-one-beta.yaml
This adds the ability to track the distance to up to 4 targets (does not try to be clever and filter by highest SNR this time).
This provides 3 new entities, distance to target, target SNR (signal to noise ratio) and target active/inactive.
Be aware that one person can have multiple targets, because the sensor can sometimes see a hand or a leg as a target if it's moving, along with the body for example. It means that when walking, one person can have 4 targets. Targets to typically settle down once seated to just a single target.
This definitely needs some testing so feedback welcome!
=> Add multiple target tracking

everything-presence-one-beta.yaml
This adds a text sensor which displays the result of sending the mmwave sensor zone/distance information. This is for debugging as it can be easy to get zones wrong and the UI doesn't reflect that.
=> Add distance status sensor

everything-presence-one.yaml
I added two new number entities to configure the PIR and Occupancy delay in the UI to make changes for new users more comfortable.
=> Replace constants for PIR & Occupancy Delay with config Entities

everything-presence-one-beta.yaml
The issue with the current beta is that there is no way to remotely include the header file which handles the target distance. See [96](https://github.com/EverythingSmartHome/everything-presence-one/issues/96)
This PR adds the code from that header file into the main YAML so there should be no problem with updates in the future.
=> Merge target distance into main YAML

everything-presence-one-beta.yaml
This fixes an issue where some of the target tracking sensors in the beta stay on the last value even when a target has disappeared and the mmWave sensor had went clear.
=> Fix mmWave Target Tracking Sensors not resetting

everything-presence-one-beta.yaml
Re-add the improv_ble feature to allow the EP1 to be configured via bluetooth
=> Re-add improv_ble

everything-presence-one-beta.yaml
This PR changes the base framework the EP1 uses from the default Arduino to ESP-IDF.
ESP-IDF seems to run much better particularly regarding WiFi and BLE being active at the same time and when trying to update over wireless which can sometimes timeout with Arduino framework.
The flash size was also getting a bit tight given all the components that are active, so this also reduces the flash size from 87.6% down to 69.4%. Nice.
=> Change framework to ESP-IDF

everything-presence-one-beta.yaml
This PR adds configurable timeouts for the PIR and Occupancy sensors to the UI instead of YAML.
Added from PR in non-beta firmware: https://github.com/EverythingSmartHome/everything-presence-one/pull/105
=> Add configurable timeouts for PIR and Occupancy

everything-presence-one-beta.yaml, everything-presence-one.yaml
This PR changes the step for the mmWave on latency to be 25ms instead of 50ms so you can get more granular control, and also reduces the maximum on latency from 60s to 2s as there shouldn't be a need for more than 2s really.
=> Change step for on latency

everything-presence-one-beta.yaml
This fixes the unit of measurement and the device class on the target X m entities so that they show up correctly in meters and also in a graph in Home Assistant, rather than a bar chart.
=> Fix unit of measurement on target distance

everything-presence-one-beta.yaml, everything-presence-one.yaml
This adds lines that will disable BLE Improv if Wifi is already connected, which should result in less connectivity issues.
=> Add BLE Improv fix

everything-presence-one-beta.yaml, everything-presence-one.yaml
Make the ESP32 LED and mmWave LED visible by default - I get asked frequently why a user can't find the LED controls in Home Assistant, which should hopefully help.
=> Make LED visible by default

everything-presence-one-beta.yaml, everything-presence-one-st.yaml, everything-presence-one.yaml
Fix negative light sensor values (a side effect of adding calibrated light sensor data) by clamping the minimum to 0.
=> Fix negative light sensor values

everything-presence-one-beta.yaml, everything-presence-one-st.yaml, everything-presence-one.yaml
Adds a quick hack to ensure that sensor startsup after boot which some users seem to report is an issue in later versions of ESPHome, where the mmWave LED is on solid, and detection does not work.
=> Ensure sensor start after boot

common/everything-presence-one-base.yaml, everything-presence-one-st-sen0609.yaml, everything-presence-one-st.yaml
Add 'platform: esphome' to device yaml, so OTA component now reads as:
```
ota:
- platform: esphome
```
In line with changes made by https://github.com/esphome/esphome/pull/6459
=> ESPHome OTA - Separate OTABackend from OTA component

common/everything-presence-one-base.yaml, everything-presence-one-beta-ble.yaml, everything-presence-one-beta.yaml, everything-presence-one-ble.yaml, everything-presence-one-sen0609-ble.yaml, everything-presence-one-sen0609.yaml, everything-presence-one-st-sen0609.yaml, everything-presence-one-st.yaml, everything-presence-one.yaml
This release mainly adds support for the new update entities in ESPHome. After updating, you will get a new "Firmware" update entity in Home Assistant which allows you to know when a new update is available from this GitHub repo. It also lets you update directly from here, without needing the ESPHome add-on to compile it for you.
=> Add update entity to Everything Presence One

common/everything-presence-one-base.yaml, everything-presence-one-beta-ble.yaml, everything-presence-one-beta.yaml, everything-presence-one-ble.yaml, everything-presence-one-sen0609-ble.yaml, everything-presence-one-sen0609.yaml, everything-presence-one.yaml
This changes the new manufacturer update entity to disabled by default, so that it is hidden. This is due to many users getting confused at the difference between the ESPHome update entity and the new manufacturer update entity. This has caused them to overwrite their encryption key and thus Home Assistant isn't able to communicate with the device.
Until their is a better way to handle the manufacturer updates when an encryption key is set, I will disable it for now to not cause so much confusion.
It also removes the http_request timeout that was set in a previous version to help with an esphome bug. The timeout in ESPHome is now 4.5s by default.
=> Disable manufacturer updates by default

static/updating.md
Fix a bug where the firmware selector on the update page would always give a bluetooth firmware even when non ble was selected
=> Fix firmware selector only allowing bluetooth firmware

common/everything-presence-one-base.yaml
Add factory reset button to allow to easily factory reset the device without needing access to a computer to flash again.
Done by holding the "boot" button for 10s, the RED LED will blink 5 times and the reset is complete.
=> Factory_reset
